BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE timetables';
    EXECUTE IMMEDIATE 'DROP TABLE users';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE timetables (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER NOT NULL,
    student1Name VARCHAR2(255),
    student1Timetable CLOB,
    student2Name VARCHAR2(255),
    student2Timetable CLOB,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
